### PR TITLE
Added simple filtering and object property value checking

### PR DESCRIPTION
**Pull request by Phando**
Added two new functions to handle filtering (_filter_) and testing for object property value testing (_hasPropertyEqual_).

```
bool hasPropertyEqual(const char* key,  const char* value) const;  
bool hasPropertyEqual(const char* key,  const JSONVar& value) const;  
bool hasPropertyEqual(const String& key,  const String& value) const;  
bool hasPropertyEqual(const String& key,  const JSONVar& value) const;  
  
JSONVar filter(const char* key, const char* value) const;
JSONVar filter(const char* key, const JSONVar& value) const;
JSONVar filter(const String& key, const String& value) const;
JSONVar filter(const String& key, const JSONVar& value) const;
```

**bool hasPropertyEqual** returns true if the JSONVar has a property named key and that key is equal to value.
_myVar[key] != null && myVal[key] == value_

**JSONVar filter** returns a JSONVar object containing objects who have properties named key and values matching value.

If no values are found it returns JSONVar(NULL, NULL)
If one value is found it returns a JSONVar Object
If multiple values are found it returns a JSONVar Array

### CODE REVIEW

**Comment by Phando** [comment]
CLA Signed, not showing though.

**Comment by per1234** [comment]
Hi @Phando. Thanks so much for your pull request!

The CLA check is done on the creator of the commits, not the creator of the pull request. The creator of the commits is determined by the GitHub user who has registered the email address specified in the commit metadata.

If you look at the commits, you can see that they are not associated with your GitHub account. This is caused by the way you have configured your local Git settings.

Please follow these instructions to resolve the issue:

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Hopefully the check will automatically pass once that has been done. If not, please comment here and we will investigate.

**Comment by Phando** [comment]
@per1234 It looks like all my submits are associated with my account.

**Comment by per1234** [comment]
The email address for the commits is:

```text
jandolina@jandolina-ltm.internal.salesforce.com
```

Have you added that email to your GitHub account according to these instructions?:

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

```text
$ git clone https://github.com/Phando/Arduino_JSON

$ cd Arduino_JSON/

$ git log -5
commit 607acab3f2195a9fb97b4d0986a6c06582e3c73c (HEAD -> master, origin/master, origin/HEAD)
Author: Joe Andolina <jandolina@jandolina-ltm.internal.salesforce.com>
Date:   Fri Mar 4 10:06:24 2022 -0800

    Updated the object filter implementation

commit 7ab7c5af463d2c0e7131f79f11fc21c0a8b84695
Author: Joe Andolina <jandolina@jandolina-ltm.internal.salesforce.com>
Date:   Fri Mar 4 09:44:19 2022 -0800

    Added cJSON_Duplicate to found items.

commit 1da99788176f26ed6db2a97e88a8038597b7da2b
Author: Joe Andolina <jandolina@jandolina-ltm.internal.salesforce.com>
Date:   Thu Mar 3 10:44:23 2022 -0800

    Added filtering and property comparison

commit 1dac1328e6beee7aa85828a6c890301ac0d91290
Author: Joe Andolina <jandolina@jandolina-ltm.internal.salesforce.com>
Date:   Wed Mar 2 11:06:08 2022 -0800

    More Work

commit 2058d1fdc6b2ee0c955e17e7c4fbfa7b9ed2d709
Author: Joe Andolina <jandolina@jandolina-ltm.internal.salesforce.com>
Date:   Wed Mar 2 10:55:36 2022 -0800

    Adding JSON helpers
```

**Review by aentinger — APPROVED** [review]
LGTM :+1:

**Pull request merged**
